### ISSUE TITLE
Links don’t work (Safari iOS)

### ISSUE THREAD

**Issue by imprevo** [ufocoder/ufostation.tech#3]
In index page links sometimes don’t work on iOS (v16.0.2). I noticed that links work as expected when animation stops. Looks like an issue with typed.js
On desktop it works fine (Chrome on Windows)
<details>
<summary>screenshot</summary>

![9B132493-2F22-4B48-AD86-5F90979ED3E9](https://user-images.githubusercontent.com/16841577/207078947-b52cb28a-3c08-4e50-a206-a13b40379e7e.jpeg)
</details>

**Comment by ufocoder** [comment]
Fixed by f7417aca6f53c61be90c633fa70a2b0587a00c14
